FROM ruby:2.3.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /app
WORKDIR /app
# Unlike the development variant, for production we run Bundler when building
# the image:
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
ADD . /app
ENV RAILS_ENV="production" PORT=80
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
